/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.starship.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StarshipEntry service. Represents a row in the &quot;StarshipEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.starship.model.impl.StarshipEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.starship.model.impl.StarshipEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StarshipEntry
 * @generated
 */
@ProviderType
public interface StarshipEntryModel
	extends BaseModel<StarshipEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a starship entry model instance should use the {@link StarshipEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this starship entry.
	 *
	 * @return the primary key of this starship entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this starship entry.
	 *
	 * @param primaryKey the primary key of this starship entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this starship entry.
	 *
	 * @return the uuid of this starship entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this starship entry.
	 *
	 * @param uuid the uuid of this starship entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the starship entry ID of this starship entry.
	 *
	 * @return the starship entry ID of this starship entry
	 */
	public long getStarshipEntryId();

	/**
	 * Sets the starship entry ID of this starship entry.
	 *
	 * @param starshipEntryId the starship entry ID of this starship entry
	 */
	public void setStarshipEntryId(long starshipEntryId);

	/**
	 * Returns the group ID of this starship entry.
	 *
	 * @return the group ID of this starship entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this starship entry.
	 *
	 * @param groupId the group ID of this starship entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this starship entry.
	 *
	 * @return the company ID of this starship entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this starship entry.
	 *
	 * @param companyId the company ID of this starship entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this starship entry.
	 *
	 * @return the user ID of this starship entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this starship entry.
	 *
	 * @param userId the user ID of this starship entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this starship entry.
	 *
	 * @return the user uuid of this starship entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this starship entry.
	 *
	 * @param userUuid the user uuid of this starship entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this starship entry.
	 *
	 * @return the user name of this starship entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this starship entry.
	 *
	 * @param userName the user name of this starship entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this starship entry.
	 *
	 * @return the create date of this starship entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this starship entry.
	 *
	 * @param createDate the create date of this starship entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this starship entry.
	 *
	 * @return the modified date of this starship entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this starship entry.
	 *
	 * @param modifiedDate the modified date of this starship entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this starship entry.
	 *
	 * @return the name of this starship entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this starship entry.
	 *
	 * @param name the name of this starship entry
	 */
	public void setName(String name);

	/**
	 * Returns the description of this starship entry.
	 *
	 * @return the description of this starship entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this starship entry.
	 *
	 * @param description the description of this starship entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the starship file image ID of this starship entry.
	 *
	 * @return the starship file image ID of this starship entry
	 */
	public long getStarshipFileImageId();

	/**
	 * Sets the starship file image ID of this starship entry.
	 *
	 * @param starshipFileImageId the starship file image ID of this starship entry
	 */
	public void setStarshipFileImageId(long starshipFileImageId);

	/**
	 * Returns the url title of this starship entry.
	 *
	 * @return the url title of this starship entry
	 */
	@AutoEscape
	public String getUrlTitle();

	/**
	 * Sets the url title of this starship entry.
	 *
	 * @param urlTitle the url title of this starship entry
	 */
	public void setUrlTitle(String urlTitle);

	/**
	 * Returns the status of this starship entry.
	 *
	 * @return the status of this starship entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this starship entry.
	 *
	 * @param status the status of this starship entry
	 */
	public void setStatus(int status);

}